!!python/object:argparse.Namespace
alpha: 0.2
batch_norm: 0
batch_size: 64
best_k: 1
checkpoint_every: 100
checkpoint_name: checkpoint
checkpoint_start_from: null
clipping_threshold_d: 0
clipping_threshold_g: 0
d_learning_rate: 0.0005
d_steps: 2
d_type: local
dataset_name: zara1
delim: ' '
dropout: 0
encoder_h_dim_d: 64
g_learning_rate: 0.0005
g_steps: 1
gpu_num: '0'
graph_lstm_hidden_size: 32
graph_network_out_dims: 32
heads: 4,1
hidden_units: '16'
l2_loss_weight: 0
loader_num_workers: 4
mlp_dim: 256
noise_dim: !!python/tuple
- 16
noise_type: gaussian
num_epochs: 200
num_iterations: 10000
num_samples_check: 5000
obs_len: 8
output_dir: /media/kevin/work/Thesis/STGAT
pred_len: 8
print_every: 5
restore_from_checkpoint: 1
seed: 72
skip: 1
timing: 0
traj_lstm_hidden_size: 32
traj_lstm_input_size: 2
use_gpu: 0
